// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAayjqLFcl0em1SybFu_y3bN-fpW7NDrQA',
    appId: '1:744980642899:android:0a2aa6d8e7456ef6d89aa6',
    messagingSenderId: '744980642899',
    projectId: 'pplant-39356',
    databaseURL: 'https://pplant-39356-default-rtdb.firebaseio.com',
    storageBucket: 'pplant-39356.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_seYNhhZ4iFbNxna9yT2_h2OauySyUWU',
    appId: '1:744980642899:ios:b3a6f694dd4c74bdd89aa6',
    messagingSenderId: '744980642899',
    projectId: 'pplant-39356',
    databaseURL: 'https://pplant-39356-default-rtdb.firebaseio.com',
    storageBucket: 'pplant-39356.appspot.com',
    iosClientId: '744980642899-g5mk7ar2g7e66savuaeks4ofle84l87q.apps.googleusercontent.com',
    iosBundleId: 'com.example.pplantProject',
  );
}
